spring:
  application:
    name: vcsuserservice
  profiles:
    active: ${SPRING_PROFILE:dev}
  cache:
    type: simple
    cache-names:
      - githubUsers

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches

github:
  api:
    base-url: https://api.github.com

logging:
  level:
    root: INFO
    com.branch.githubuserservice: INFO