logging:
  level:
    root: INFO
    com.branch.vcsuserservice: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
